lab25: course.o container.o course_main.o 
	g++ -o lab25 course.o container.o course_main.o
course.o: course.cpp
	g++ -c course.cpp
container.o: container.cpp
	g++ -c container.cpp
course_main.o: course_main.cpp
	g++ -c course_main.cpp

clean:
	rm *.o

